/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.textArea;

import gestion.dto.MedicoDTO;
import java.util.List;

/**
 *
 * @author ck
 */
public class TxtAreaMedicos extends javax.swing.JDialog {

    private List<MedicoDTO> listM;
    private String txt = "";

    /**
     * Creates new form TxtAreaMedicos
     *
     * @param parent
     * @param modal
     * @param medicos
     */
    @SuppressWarnings("empty-statement")
    public TxtAreaMedicos(javax.swing.JDialog parent, boolean modal, List<MedicoDTO> medicos) {
        super(parent, modal);
        initComponents();
        setTitle("GESTION HOSPITALARIA");
        setLocationRelativeTo(null);
        listM = medicos;
        for (int i = 0; i < medicos.size(); i++) {
            txt += medicos.get(i).getDatos();
        };
        TxtA.setText(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Médicos del hospital");

        TxtA.setEditable(false);
        TxtA.setColumns(20);
        TxtA.setRows(5);
        TxtA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(TxtA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
